[general]
	import = ["~/.config/alacritty/alacritty.toml"]

[colors]
	draw_bold_text_with_bright_colors = true

[terminal]
	shell = { program = "neomutt", args = [] }

[window.class]
	general = "neomuttTerm"
	instance = "neomuttTerm"
